/* This Proc Format program was automatically generated by Stat/Transfer ver.10.1.1866.0714 */

/* ENCODING CP1252 */



libname library 'c:/users/rosie/documents/new projects/knowledge networks where couples meet/web site documentation prep v3, second follow-up/sas version 3.04/' ;

proc format library = library ;
   value LABB
      -2 = 'not asked'  
      -1 = 'refused' ;
   value PPAGECAT
      1 = '18-24'  
      2 = '25-34'  
      3 = '35-44'  
      4 = '45-54'  
      5 = '55-64'  
      6 = '65-74'  
      7 = '75+'  
      99 = 'under 18' ;
   value PPAGECT4F
      1 = '18-29'  
      2 = '30-44'  
      3 = '45-59'  
      4 = '60+'  
      99 = 'under 18' ;
   value PPEDUC
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'no formal education'  
      2 = '1st, 2nd, 3rd, or 4th grade'  
      3 = '5th or 6th grade'  
      4 = '7th or 8th grade'  
      5 = '9th grade'  
      6 = '10th grade'  
      7 = '11th grade'  
      8 = '12th grade no diploma'  
      9 = 'high school graduate - high school diploma or the equivalent (ged)'  
      10 = 'some college, no degree'  
      11 = 'associate degree'  
      12 = 'bachelors degree'  
      13 = 'masters degree'  
      14 = 'professional or doctorate degree' ;
   value PPEDUCAT
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'less than high school'  
      2 = 'high school'  
      3 = 'some college'  
      4 = 'bachelor''s degree or higher' ;
   value PPETHM
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'white, non-hispanic'  
      2 = 'black, non-hispanic'  
      3 = 'other, non-hispanic'  
      4 = 'hispanic'  
      5 = '2+ races, non-hispanic' ;
   value PPGENDER
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'male'  
      2 = 'female' ;
   value PPHHHEAD
      -2 = 'not asked'  
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value PPHOUSE
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'a one-family house detached from any other house'  
      2 = 'a one-family house attached to one or more houses'  
      3 = 'a building with 2 or more apartments'  
      4 = 'a mobile home'  
      5 = 'boat, rv, van, etc.' ;
   value PPINCIMP
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'less than $5,000'  
      2 = '$5,000 to $7,499'  
      3 = '$7,500 to $9,999'  
      4 = '$10,000 to $12,499'  
      5 = '$12,500 to $14,999'  
      6 = '$15,000 to $19,999'  
      7 = '$20,000 to $24,999'  
      8 = '$25,000 to $29,999'  
      9 = '$30,000 to $34,999'  
      10 = '$35,000 to $39,999'  
      11 = '$40,000 to $49,999'  
      12 = '$50,000 to $59,999'  
      13 = '$60,000 to $74,999'  
      14 = '$75,000 to $84,999'  
      15 = '$85,000 to $99,999'  
      16 = '$100,000 to $124,999'  
      17 = '$125,000 to $149,999'  
      18 = '$150,000 to $174,999'  
      19 = '$175,000 or more' ;
   value PPMARIT
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'married'  
      2 = 'widowed'  
      3 = 'divorced'  
      4 = 'separated'  
      5 = 'never married'  
      6 = 'living with partner' ;
   value PPMSACAT
      -2 = 'not asked'  
      -1 = 'refused'  
      0 = 'non-metro'  
      1 = 'metro' ;
   value PPREG4F
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'northeast'  
      2 = 'midwest'  
      3 = 'south'  
      4 = 'west' ;
   value PPREG9F
      1 = 'new england'  
      2 = 'mid-atlantic'  
      3 = 'east-north central'  
      4 = 'west-north central'  
      5 = 'south atlantic'  
      6 = 'east-south central'  
      7 = 'west-south central'  
      8 = 'mountain'  
      9 = 'pacific' ;
   value PPRENT
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'owned or being bought by you or someone in your household'  
      2 = 'rented for cash'  
      3 = 'occupied without payment of cash rent' ;
   value PPWORK
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'working - as a paid employee'  
      2 = 'working - self-employed'  
      3 = 'not working - on temporary layoff from a job'  
      4 = 'not working - looking for work'  
      5 = 'not working - retired'  
      6 = 'not working - disabled'  
      7 = 'not working - other' ;
   value PPNET
      0 = 'no'  
      1 = 'yes' ;
   value PPQ14ARACE
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'white'  
      2 = 'black, or  african american'  
      3 = 'american indian or alaska native'  
      4 = 'asian indian'  
      5 = 'chinese'  
      6 = 'filipino'  
      7 = 'japanese'  
      8 = 'korean'  
      9 = 'vietnamese'  
      10 = 'other asian'  
      11 = 'native hawaiian'  
      12 = 'guamanian or chamorro'  
      13 = 'samoan'  
      14 = 'other pacific islander'  
      15 = 'some other race' ;
   value PPHISPAN
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'no, i am not'  
      2 = 'yes, mexican, mexican-american, chicano'  
      3 = 'yes, puerto rican'  
      4 = 'yes, cuban'  
      5 = 'yes, central american'  
      6 = 'yes, south american'  
      7 = 'yes, caribbean'  
      8 = 'yes, other spanish/hispanic/latino' ;
   value LABC
      -2 = 'not asked'  
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value PPPPPA0042F
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'yes, friends'  
      2 = 'yes, relatives'  
      3 = 'yes, both'  
      4 = 'no'  
      5 = 'i would prefer to not answer this question' ;
   value PPPARTYID3F
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'republican'  
      2 = 'other'  
      3 = 'democrat' ;
   value PPPPPA0306F
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value PPPPPA0046F
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'baptist-any denomination'  
      2 = 'protestant (e.g., methodist, lutheran, presbyterian, episcopal)'  
      3 = 'catholic'  
      4 = 'mormon'  
      5 = 'jewish'  
      6 = 'muslim'  
      7 = 'hindu'  
      8 = 'buddhist'  
      9 = 'pentecostal'  
      10 = 'eastern orthodox'  
      11 = 'other christian'  
      12 = 'other non-christian, please specify:'  
      13 = 'none' ;
   value PPHHCOMP11_MEMBER2_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER3_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER4_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER5_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER6_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER7_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER8_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER9_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER10_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER11_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER12_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER13_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER14_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER15_GENDER
      -1 = 'please select'  
      2 = 'male'  
      3 = 'female' ;
   value PPHHCOMP11_MEMBER2_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER3_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER4_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER5_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER6_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER7_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER8_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER9_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER10_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER11_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER12_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER13_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER14_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value PPHHCOMP11_MEMBER15_RELATIONSHIP
      -1 = 'please select'  
      2 = 'spouse'  
      3 = 'child (biological, adopted, or stepchild)'  
      4 = 'grandchild'  
      5 = 'parent'  
      6 = 'sibling'  
      7 = 'other relative'  
      8 = 'unmarried partner'  
      9 = 'housemate/roommate'  
      10 = 'other non-relative' ;
   value IRB_CONSENT
      -1 = 'refused'  
      1 = 'yes, i agree to participate'  
      2 = 'no, i don''t agree to participate' ;
   value QFLAG
      1 = 'partnered'  
      2 = 'no spouse or partner or otherwise unqualified' ;
   value GLBSTATUS
      0 = 'not glb'  
      1 = 'glb' ;
   value PPPA0043F
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no'  
      3 = 'i would prefer to not answer this question' ;
   value RECSOURCE
      1 = 'gen pop sample'  
      2 = 'glb augment sample'  
      3 = 'glb withdrawn sample'  
      4 = 'glb item refused sample' ;
   value S1F
      -1 = 'refused'  
      1 = 'yes, i am married'  
      2 = 'no, i am not married' ;
   value S1A
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no'  
      3 = 'i would prefer not to answer this question' ;
   value S2F
      -1 = 'refused'  
      1 = 'yes, i have a sexual partner (boyfriend or girlfriend)'  
      2 = 'i have a romantic partner who is not yet a sexual partner'  
      3 = 'no, i am single, with no boyfriend, no girlfriend and no romantic or sexual partner' ;
   value Q3_CODES
      -1 = 'refused' ;
   value Q4F
      -1 = 'refused'  
      1 = 'male'  
      2 = 'female'  
      3 = 'other, please specify' ;
   value Q5F
      -1 = 'refused'  
      1 = 'yes, we are a same-sex couple'  
      2 = 'no, we are an opposite-sex couple' ;
   value Q6A
      -1 = 'refused'  
      1 = 'no (not latino or hispanic)'  
      2 = 'yes, mexican, mexican american, chicano'  
      3 = 'yes, puerto rican'  
      4 = 'yes, cuban'  
      5 = 'yes, other latino/hispanic' ;
   value Q6B
      -1 = 'refused'  
      1 = 'white'  
      2 = 'black or african american'  
      3 = 'american indian, aleut, or eskimo'  
      4 = 'asian or pacific islander'  
      5 = 'other (please specify)' ;
   value Q7A
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value Q7B
      -1 = 'refused'  
      1 = 'baptist - any denomination'  
      2 = 'protestant (e.g. methodist, lutheran, presbyterian, episcopal)'  
      3 = 'catholic'  
      4 = 'mormon'  
      5 = 'jewish'  
      6 = 'muslim'  
      7 = 'hindu'  
      8 = 'buddhist'  
      9 = 'pentecostal'  
      10 = 'eastern orthodox'  
      11 = 'other christian'  
      12 = 'other non-christian, please specify'  
      13 = 'none' ;
   value Q8A
      -1 = 'refused'  
      1 = 'yes, the same'  
      2 = 'no, has changed religions' ;
   value Q8B
      -1 = 'refused'  
      1 = 'baptist - any denomination'  
      2 = 'protestant (e.g. methodist, lutheran, presbyterian, episcopal)'  
      3 = 'catholic'  
      4 = 'mormon'  
      5 = 'jewish'  
      6 = 'muslim'  
      7 = 'hindu'  
      8 = 'buddhist'  
      9 = 'pentecostal'  
      10 = 'eastern orthodox'  
      11 = 'other christian'  
      12 = 'other non-christian, please specify'  
      13 = 'none' ;
   value Q10F
      -1 = 'refused'  
      1 = 'no formal education'  
      2 = '1st - 4th grade'  
      3 = '5th or 6th grade'  
      4 = '7th or 8th grade'  
      5 = '9th grade'  
      6 = '10th grade'  
      7 = '11th grade'  
      8 = '12th grade no diploma'  
      9 = 'hs graduate or ged'  
      10 = 'some college, no degree'  
      11 = 'associate degree'  
      12 = 'bachelor''s degree'  
      13 = 'master''s degree'  
      14 = 'professional or doctorate degree' ;
   value Q11F
      -1 = 'refused'  
      1 = 'no formal education'  
      2 = '1st - 4th grade'  
      3 = '5th or 6th grade'  
      4 = '7th or 8th grade'  
      5 = '9th grade'  
      6 = '10th grade'  
      7 = '11th grade'  
      8 = '12th grade no diploma'  
      9 = 'hs graduate or ged'  
      10 = 'some college, no degree'  
      11 = 'associate degree'  
      12 = 'bachelor''s degree'  
      13 = 'master''s degree'  
      14 = 'professional or doctorate degree' ;
   value Q12F
      -1 = 'refused'  
      1 = 'republican'  
      2 = 'democrat'  
      3 = 'independent'  
      4 = 'another party, please specify'  
      5 = 'no preference' ;
   value Q13A
      -1 = 'refused'  
      1 = 'yes, the same'  
      2 = 'no, i have changed religions' ;
   value Q13B
      -1 = 'refused'  
      1 = 'baptist - any denomination'  
      2 = 'protestant (e.g. methodist, lutheran, presbyterian, episcopal)'  
      3 = 'catholic'  
      4 = 'mormon'  
      5 = 'jewish'  
      6 = 'muslim'  
      7 = 'hindu'  
      8 = 'buddhist'  
      9 = 'pentecostal'  
      10 = 'eastern orthodox'  
      11 = 'other christian'  
      12 = 'other non-christian, please specify'  
      13 = 'none' ;
   value Q14F
      -1 = 'refused'  
      1 = 'no formal education'  
      2 = '1st - 4th grade'  
      3 = '5th or 6th grade'  
      4 = '7th or 8th grade'  
      5 = '9th grade'  
      6 = '10th grade'  
      7 = '11th grade'  
      8 = '12th grade no diploma'  
      9 = 'hs graduate or ged'  
      10 = 'some college, no degree'  
      11 = 'associate degree'  
      12 = 'bachelor''s degree'  
      13 = 'master''s degree'  
      14 = 'professional or doctorate degree' ;
   value Q15A1_COMPRESSED
      -1 = 'refused'  
      1 = 'United States'  
      2 = 'all others' ;
   value Q16_LBL
      -1 = 'refused' ;
   value Q17A
      -1 = 'refused'  
      1 = 'once (this is my first marriage)'  
      2 = 'twice'  
      3 = 'three times'  
      4 = 'four or more times' ;
   value Q17B
      -1 = 'refused'  
      1 = 'never married'  
      2 = 'once'  
      3 = 'twice'  
      4 = 'three times'  
      5 = 'four or more times' ;
   value Q17C
      -1 = 'refused'  
      1 = 'i am sexually attracted only to men'  
      2 = 'i am mostly sexually attracted to men, less often sexually attracted to women'  
      3 = 'i am equally sexually attracted to men and women'  
      4 = 'i am mostly sexually attracted to women, less often sexually attracted to men'  
      5 = 'i am sexually attracted only to women' ;
   value Q17D
      -1 = 'refused'  
      1 = 'i am sexually attracted only to women'  
      2 = 'i am mostly sexually attracted to women, less often sexually attracted to men'  
      3 = 'i am equally sexually attracted to men and women'  
      4 = 'i am mostly sexually attracted to men, less often sexually attracted to women'  
      5 = 'i am sexually attracted only to men' ;
   value GENDER_ATTRACTION
      1 = 'opposite gender only'  
      2 = 'mostly opposite'  
      3 = 'both genders equally'  
      4 = 'same gender mostly'  
      5 = 'only same gender' ;
   value Q18A_1F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q18A_2F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q18A_3_LBL_NEW
      -1 = 'refused'  
      0 = 'have either DP or CU'  
      1 = 'have neither DP nor CU' ;
   value Q18A_REFUSED
      0 = 'no'  
      1 = 'yes' ;
   value Q18B_CODES
      -1 = 'refused' ;
   value Q18C_CODES
      -1 = 'refused' ;
   value Q19F
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value Q20F
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value REFUSAL
      1 = 'refused' ;
   value Q22F
      -1 = 'refused'  
      1 = 'less than one month'  
      2 = '1-3 months'  
      3 = '4-6 months'  
      4 = '7 months - 1 year'  
      5 = 'more than 1 year, less than 2 years'  
      6 = 'more than 2 years, less than 3 years'  
      7 = '3 years or more' ;
   value Q23F
      -1 = 'refused'  
      1 = 'i earned more'  
      2 = 'we earned about the same amount'  
      3 = 'partner earned more' ;
   value Q24_CODES
      -1 = 'refused'  
      1 = 'answered but refused to provide information' ;
   value Q25F
      -1 = 'refused'  
      1 = 'same high school'  
      2 = 'different high school' ;
   value Q26F
      -1 = 'refused'  
      1 = 'attended same college or university'  
      2 = 'did not attend same college or university' ;
   value Q27F
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value Q28F
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value Q29F
      -1 = 'refused'  
      1 = 'father and mother'  
      2 = 'father only'  
      3 = 'mother only'  
      4 = 'neither father nor mother are alive' ;
   value Q30F
      -1 = 'refused'  
      1 = 'approve'  
      2 = 'neither approve nor disapprove'  
      3 = 'disapprove'  
      4 = 'do not know' ;
   value Q31_1F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q31_2F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q31_3F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q31_4F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q31_5F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q31_6F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q31_7F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q31_8F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q31_9F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value YES_NO
      0 = 'No'  
      1 = 'Yes' ;
   value Q32F
      -1 = 'refused'  
      1 = 'yes, a social networking site (like facebook or myspace)'  
      2 = 'no, we did not meet through the internet'  
      3 = 'yes, an internet dating or matchmaking site (like eharmony or match.com)'  
      4 = 'yes, an internet classified advertising site (like craigslist)'  
      5 = 'yes, an internet chat room'  
      6 = 'yes, a different kind of internet service' ;
   value Q33_1F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q33_2F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q33_3F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q33_4F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q33_5F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q33_6F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q33_7F
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value Q34F
      -1 = 'refused'  
      1 = 'excellent'  
      2 = 'good'  
      3 = 'fair'  
      4 = 'poor'  
      5 = 'very poor' ;
   value Q35_CODES
      -1 = 'refused' ;
   value SUMMARY_Q24_INTERNET
      0 = 'met offline'  
      1 = 'met online' ;
   value M_NOT_REALLY
      0 = 'married'  
      1 = 'not legally married' ;
   value NOT_REALLY
      0 = 'real civ union or dom partnership'  
      1 = 'perhaps not real civ union or dom partnership' ;
   value PARTNER_DECEASED
      0 = 'not deceased'  
      1 = 'apparently deceased' ;
   value HOW_MET_ONLINE_LBL
      1 = 'reconnected: already knew partner but reconnected online'  
      2 = 'Mediated: Online connection was mediated by friends, family, or others'  
      3 = 'Previously Strangers: Before online connection respondent and partner were strangers'  
      4 = 'We cannot tell from the existed data whether the respondent and partner knew each other prior to online connection'  
      5 = 'Probably Did Not meet partner online, despite positive answer to q32 or q24' ;
   value EITHER_INTERNET_ADJUSTED_LBL
      -1 = 'probably not met online, q32 and q24 disagree'  
      0 = 'not met online'  
      1 = 'met online' ;
   value SAME_SEX_COUPLE
      0 = 'different sex couple'  
      1 = 'same-sex couple' ;
   value HOW_LONG_AGO_FIRST_MET_CAT
      1 = '0-2'  
      2 = '3-5'  
      3 = '6-10'  
      4 = '11-15'  
      5 = '16-20'  
      6 = '21-30'  
      7 = '31+' ;
   value RACE_LBL
      1 = 'NH white'  
      2 = ' NH black'  
      3 = ' NH Amer Indian'  
      4 = ' NH Asian Pac Islander'  
      5 = ' NH Other'  
      6 = 'Hispanic' ;
   value FRIENDS
      0 = 'not met through friends'  
      1 = 'meet through friends' ;
   value FAMILY
      0 = 'not met through family'  
      1 = 'met through family' ;
   value NEIGHBORS
      0 = 'did not meet through or as neighbors'  
      1 = 'met through or as neighbors' ;
   value RELIG_CAT
      1 = 'Protestant or oth Christian'  
      2 = 'Catholic'  
      3 = 'Jewish'  
      4 = 'Neither Christian nor Jewish'  
      5 = 'No religion' ;
   value MARRIED
      0 = 'not married'  
      1 = 'married' ;
   value PARENTAL_APPROVAL
      0 = 'don''t approve or don''t know'  
      1 = 'approve' ;
   value Q15A1F
      -1 = 'refused'  
      1 = 'united states'  
      2 = 'cambodia'  
      3 = 'canada'  
      4 = 'china'  
      5 = 'colombia'  
      6 = 'cuba'  
      7 = 'dominican republic'  
      8 = 'ecuador'  
      9 = 'el salvador'  
      10 = 'former yugoslavia'  
      11 = 'france'  
      12 = 'germany'  
      13 = 'great britain'  
      14 = 'greece'  
      15 = 'guatemala'  
      16 = 'guyana'  
      17 = 'haiti'  
      18 = 'honduras'  
      19 = 'hungary'  
      20 = 'india'  
      21 = 'iran'  
      22 = 'ireland'  
      23 = 'italy'  
      24 = 'jamaica'  
      25 = 'japan'  
      26 = 'korea'  
      27 = 'laos'  
      28 = 'mexico'  
      29 = 'nicaragua'  
      30 = 'peru'  
      31 = 'philippines'  
      32 = 'poland'  
      33 = 'portugal'  
      34 = 'russia'  
      35 = 'taiwan'  
      36 = 'thailand'  
      37 = 'trinidad and tobago'  
      38 = 'vietnam'  
      39 = 'another country, please specify' ;
   value US_RAISED
      0 = 'raised outside US'  
      1 = 'raised in US' ;
   value RELATIONSHIP_QUALITY
      1 = 'very poor'  
      2 = 'poor'  
      3 = 'fair'  
      4 = 'good'  
      5 = 'excellent' ;
   value P2_AFTERP1F
      0 = 'No second background survey'  
      1 = 'Yes second background survey' ;
   value W2C_PPHHHEAD
      -2 = 'not asked'  
      -1 = 'refused'  
      0 = 'no'  
      1 = 'yes' ;
   value W2C_LABB
      -2 = 'not asked'  
      -1 = 'refused' ;
   value W2C_PPHOUSE
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'a one-family house detached from any other house'  
      2 = 'a one-family house attached to one or more houses'  
      3 = 'a building with 2 or more apartments'  
      4 = 'a mobile home'  
      5 = 'boat, rv, van, etc.' ;
   value W2C_PPINCIMP
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'less than $5,000'  
      2 = '$5,000 to $7,499'  
      3 = '$7,500 to $9,999'  
      4 = '$10,000 to $12,499'  
      5 = '$12,500 to $14,999'  
      6 = '$15,000 to $19,999'  
      7 = '$20,000 to $24,999'  
      8 = '$25,000 to $29,999'  
      9 = '$30,000 to $34,999'  
      10 = '$35,000 to $39,999'  
      11 = '$40,000 to $49,999'  
      12 = '$50,000 to $59,999'  
      13 = '$60,000 to $74,999'  
      14 = '$75,000 to $84,999'  
      15 = '$85,000 to $99,999'  
      16 = '$100,000 to $124,999'  
      17 = '$125,000 to $149,999'  
      18 = '$150,000 to $174,999'  
      19 = '$175,000 or more' ;
   value W2C_PPMARIT
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'married'  
      2 = 'widowed'  
      3 = 'divorced'  
      4 = 'separated'  
      5 = 'never married'  
      6 = 'living with partner' ;
   value W2C_PPMSACAT
      -2 = 'not asked'  
      -1 = 'refused'  
      0 = 'non-metro'  
      1 = 'metro' ;
   value W2C_PPEDUC
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'no formal education'  
      2 = '1st, 2nd, 3rd, or 4th grade'  
      3 = '5th or 6th grade'  
      4 = '7th or 8th grade'  
      5 = '9th grade'  
      6 = '10th grade'  
      7 = '11th grade'  
      8 = '12th grade no diploma'  
      9 = 'high school graduate - high school diploma or the equivalent (ged)'  
      10 = 'some college, no degree'  
      11 = 'associate degree'  
      12 = 'bachelors degree'  
      13 = 'masters degree'  
      14 = 'professional or doctorate degree' ;
   value W2C_PPEDUCAT
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'less than high school'  
      2 = 'high school'  
      3 = 'some college'  
      4 = 'bachelor''s degree or higher' ;
   value W2C_PPETHM
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'white, non-hispanic'  
      2 = 'black, non-hispanic'  
      3 = 'other, non-hispanic'  
      4 = 'hispanic'  
      5 = '2+ races, non-hispanic' ;
   value W2C_PPREG4F
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'northeast'  
      2 = 'midwest'  
      3 = 'south'  
      4 = 'west' ;
   value W2C_PPREG9F
      1 = 'new england'  
      2 = 'mid-atlantic'  
      3 = 'east-north central'  
      4 = 'west-north central'  
      5 = 'south atlantic'  
      6 = 'east-south central'  
      7 = 'west-south central'  
      8 = 'mountain'  
      9 = 'pacific' ;
   value W2C_PPRENT
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'owned or being bought by you or someone in your household'  
      2 = 'rented for cash'  
      3 = 'occupied without payment of cash rent' ;
   value W2C_PPWORK
      -2 = 'not asked'  
      -1 = 'refused'  
      1 = 'working - as a paid employee'  
      2 = 'working - self-employed'  
      3 = 'not working - on temporary layoff from a job'  
      4 = 'not working - looking for work'  
      5 = 'not working - retired'  
      6 = 'not working - disabled'  
      7 = 'not working - other' ;
   value W2C_PPNET
      0 = 'no'  
      1 = 'yes' ;
   value W2C_IGDR1F
      0 = 'value not imputed'  
      1 = 'value imputed' ;
   value W2C_IEDUC1F
      0 = 'value not imputed'  
      1 = 'value imputed' ;
   value W2C_IGDR2F
      0 = 'value not imputed'  
      1 = 'value imputed' ;
   value W2C_IEDUC2F
      0 = 'value not imputed'  
      1 = 'value imputed' ;
   value W2C_DECEASED
      0 = 'not deceased'  
      1 = 'apparently deceased' ;
   value W2C_MULTINAME
      1 = 'includes multiple names' ;
   value W2C_PANELSTAT
      1 = 'active kn panelist'  
      2 = 'withdrawn kn panelist' ;
   value W2C_DONOTCONTACT
      1 = 'withdrawn case on noncontact list'  
      2 = 'all other cases' ;
   value W2C_ASSIGNED
      1 = 'assigned to survey'  
      2 = 'not assigned to survey' ;
   value W2C_F1COMPLETE
      0 = 'did not complete followup survey'  
      1 = 'completed followup survey' ;
   value W2C_XMARRY
      1 = 'married'  
      2 = 'partnered' ;
   value W2C_XSS
      1 = 'yes, qualified to ask about new domestic parterships'  
      2 = 'no' ;
   value W2C_SOURCE
      1 = 'online'  
      2 = 'telephone' ;
   value W2C_Q1F
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W2C_Q2F
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W2C_Q3F
      -1 = 'refused'  
      1 = 'divorce'  
      2 = 'separation with no divorce'  
      3 = '[partner] passed away, is deceased' ;
   value W2C_Q4F
      -1 = 'refused'  
      1 = 'i wanted the [divorce/separation] more'  
      2 = '[partner] wanted the [divorce/separation] more'  
      3 = 'we both equally wanted the [divorce/separation]' ;
   value W2C_Q5F
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W2C_Q6F
      -1 = 'refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W2C_Q7F
      -1 = 'refused'  
      1 = 'yes, married [partner]'  
      2 = 'no, did not marry [partner]' ;
   value W2C_Q8F
      -1 = 'refused'  
      1 = 'no, we have not gotten a domestic partnership or civil union agreement'  
      2 = 'yes, we have gotten a domestic partnership or civil union agreement' ;
   value W2C_Q9F
      -1 = 'refused'  
      1 = 'we broke up'  
      2 = '[partner] passed away, is deceased'  
      3 = 'other (please describe)' ;
   value W2C_Q10F
      -1 = 'refused'  
      1 = 'i wanted to break up more'  
      2 = '[partner] wanted to break up more'  
      3 = 'we both equally wanted to break up' ;
   value BROKE_UP
      0 = 'still together'  
      1 = 'broke up'  
      2 = 'partner passed away' ;
   value INTERSTATE_MOVER
      0 = 'stayer'  
      1 = 'mover' ;
   value PP3_NEWER
      0 = 'no, newer pp3 data is Not available'  
      1 = 'Yes, pp3 data is newer and available' ;
   value COMBO_BREAKUP
      0 = 'still together, or lost to follow-up, or partner deceased'  
      1 = 'broke up' ;
   value W3_BROKEUP_ACTUAL
      0 = 'still together'  
      1 = 'broke up'  
      2 = 'partner deceased' ;
   value W3_XQUALIFIED
      0 = 'unqualified bc unpartnered at main survery'  
      1 = 'Qualified for follow-up at wave3'  
      2 = 'unqualified bc broke up at wave 2' ;
   value W3_MULTINAME
      1 = 'reported multiple partner names in main survey' ;
   value W3_XSS
      1 = 'yes'  
      2 = 'no' ;
   value W3_XLAST
      1 = '1 year ago'  
      2 = '2 years ago' ;
   value W3_STATUS
      1 = 'active member of KN panel'  
      2 = 'subject withdrew from KN panel'  
      3 = 'subject retired from KN panel, KN decision'  
      4 = 'Do Not Contact- subject withdrew and asked not to be contacted' ;
   value W3_COMPLETE
      0 = 'no'  
      1 = 'yes' ;
   value W3_SOURCE
      1 = 'Online'  
      2 = 'Telephone' ;
   value XMARRY
      1 = 'Married'  
      2 = 'Partnered' ;
   value XTYPE
      1 = 'same sex couple'  
      2 = 'heterosexual couple' ;
   value W3_Q1F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W3_Q2F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W3_Q3F
      -1 = 'Refused'  
      1 = 'divorce'  
      2 = 'separation with no divorce'  
      3 = '[xNameP] passed away, is deceased' ;
   value W3_Q4F
      -1 = 'Refused'  
      1 = 'I wanted the [divorce/separation] more.'  
      2 = '[xNameP] wanted the [divorce/separation] more.'  
      3 = 'We both equally wanted the [divorce/separation].' ;
   value MBTIMING
      -1 = 'Please Select'  
      2 = '2009'  
      3 = '2010'  
      4 = '2011' ;
   value MONTH
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W3_Q5F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W3_Q6F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W3_Q7F
      -1 = 'Refused'  
      1 = 'yes, married [xNameP]'  
      2 = 'no, did not marry [xNameP]' ;
   value W3_Q8F
      -1 = 'Refused'  
      1 = 'No, we have not gotten a domestic partnership or civil union agreement'  
      2 = 'Yes, we have gotten a domestic partnership or civil union agreement' ;
   value W3_Q9F
      -1 = 'Refused'  
      1 = 'We broke up'  
      2 = '[xNameP] passed away, is deceased'  
      3 = 'Other (please describe)' ;
   value W3_Q10F
      -1 = 'Refused'  
      1 = 'I wanted to break up more'  
      2 = '[xNameP] wanted to break up more'  
      3 = 'We both equally wanted to break up' ;
   value NONMBTIM
      -1 = 'Please Select'  
      2 = '2009'  
      3 = '2010'  
      4 = '2011' ;

proc datasets library = library ;
modify HCMST_ver_304_SAS;
   format     ppage LABB.;
   format  ppagecat PPAGECAT.;
   format  ppagect4 PPAGECT4F.;
   format    ppeduc PPEDUC.;
   format  ppeducat PPEDUCAT.;
   format    ppethm PPETHM.;
   format  ppgender PPGENDER.;
   format  pphhhead PPHHHEAD.;
   format   pphouse PPHOUSE.;
   format  ppincimp PPINCIMP.;
   format   ppmarit PPMARIT.;
   format  ppmsacat PPMSACAT.;
   format    ppreg4 PPREG4F.;
   format    ppreg9 PPREG9F.;
   format    pprent PPRENT.;
   format     ppt01 LABB.;
   format   ppt1317 LABB.;
   format   ppt18ov LABB.;
   format     ppt25 LABB.;
   format    ppt612 LABB.;
   format    ppwork PPWORK.;
   format     ppnet PPNET.;
   format ppq14arace PPQ14ARACE.;
   format  pphispan PPHISPAN.;
   format pprace_white LABC.;
   format pprace_black LABC.;
   format pprace_nativeamerican LABC.;
   format pprace_asianindian LABC.;
   format pprace_chinese LABC.;
   format pprace_filipino LABC.;
   format pprace_japanese LABC.;
   format pprace_korean LABC.;
   format pprace_vietnamese LABC.;
   format pprace_otherasian LABC.;
   format pprace_hawaiian LABC.;
   format pprace_guamanian LABC.;
   format pprace_samoan LABC.;
   format pprace_otherpacificislander LABC.;
   format pprace_someotherrace LABC.;
   format papglb_friend PPPPPA0042F.;
   format pppartyid3 PPPARTYID3F.;
   format papevangelical PPPPPA0306F.;
   format papreligion PPPPPA0046F.;
   format pphhcomp11_member2_gender PPHHCOMP11_MEMBER2_GENDER.;
   format pphhcomp11_member3_gender PPHHCOMP11_MEMBER3_GENDER.;
   format pphhcomp11_member4_gender PPHHCOMP11_MEMBER4_GENDER.;
   format pphhcomp11_member5_gender PPHHCOMP11_MEMBER5_GENDER.;
   format pphhcomp11_member6_gender PPHHCOMP11_MEMBER6_GENDER.;
   format pphhcomp11_member7_gender PPHHCOMP11_MEMBER7_GENDER.;
   format pphhcomp11_member8_gender PPHHCOMP11_MEMBER8_GENDER.;
   format pphhcomp11_member9_gender PPHHCOMP11_MEMBER9_GENDER.;
   format pphhcomp11_member10_gender PPHHCOMP11_MEMBER10_GENDER.;
   format pphhcomp11_member11_gender PPHHCOMP11_MEMBER11_GENDER.;
   format pphhcomp11_member12_gender PPHHCOMP11_MEMBER12_GENDER.;
   format pphhcomp11_member13_gender PPHHCOMP11_MEMBER13_GENDER.;
   format pphhcomp11_member14_gender PPHHCOMP11_MEMBER14_GENDER.;
   format pphhcomp11_member15_gender PPHHCOMP11_MEMBER15_GENDER.;
   format pphhcomp11_member2_relationship PPHHCOMP11_MEMBER2_RELATIONSHIP.;
   format pphhcomp11_member3_relationship PPHHCOMP11_MEMBER3_RELATIONSHIP.;
   format pphhcomp11_member4_relationship PPHHCOMP11_MEMBER4_RELATIONSHIP.;
   format pphhcomp11_member5_relationship PPHHCOMP11_MEMBER5_RELATIONSHIP.;
   format pphhcomp11_member6_relationship PPHHCOMP11_MEMBER6_RELATIONSHIP.;
   format pphhcomp11_member7_relationship PPHHCOMP11_MEMBER7_RELATIONSHIP.;
   format pphhcomp11_member8_relationship PPHHCOMP11_MEMBER8_RELATIONSHIP.;
   format pphhcomp11_member9_relationship PPHHCOMP11_MEMBER9_RELATIONSHIP.;
   format pphhcomp11_member10_relationship PPHHCOMP11_MEMBER10_RELATIONSHIP.;
   format pphhcomp11_member11_relationship PPHHCOMP11_MEMBER11_RELATIONSHIP.;
   format pphhcomp11_member12_relationship PPHHCOMP11_MEMBER12_RELATIONSHIP.;
   format pphhcomp11_member13_relationship PPHHCOMP11_MEMBER13_RELATIONSHIP.;
   format pphhcomp11_member14_relationship PPHHCOMP11_MEMBER14_RELATIONSHIP.;
   format pphhcomp11_member15_relationship PPHHCOMP11_MEMBER15_RELATIONSHIP.;
   format irb_consent IRB_CONSENT.;
   format     qflag QFLAG.;
   format glbstatus GLBSTATUS.;
   format papglb_status PPPA0043F.;
   format recsource RECSOURCE.;
   format        s1 S1F.;
   format       s1a S1A.;
   format        s2 S2F.;
   format  q3_codes Q3_CODES.;
   format        q4 Q4F.;
   format        q5 Q5F.;
   format       q6a Q6A.;
   format       q6b Q6B.;
   format       q7a Q7A.;
   format       q7b Q7B.;
   format       q8a Q8A.;
   format       q8b Q8B.;
   format       q10 Q10F.;
   format       q11 Q11F.;
   format       q12 Q12F.;
   format      q13a Q13A.;
   format      q13b Q13B.;
   format       q14 Q14F.;
   format q15a1_compressed Q15A1_COMPRESSED.;
   format       q16 Q16_LBL.;
   format      q17a Q17A.;
   format      q17b Q17B.;
   format      q17c Q17C.;
   format      q17d Q17D.;
   format gender_attraction GENDER_ATTRACTION.;
   format    q18a_1 Q18A_1F.;
   format    q18a_2 Q18A_2F.;
   format    q18a_3 Q18A_3_LBL_NEW.;
   format q18a_refused Q18A_REFUSED.;
   format q18b_codes Q18B_CODES.;
   format q18c_codes Q18C_CODES.;
   format       q19 Q19F.;
   format       q20 Q20F.;
   format q21a_refusal REFUSAL.;
   format q21b_refusal REFUSAL.;
   format q21c_refusal REFUSAL.;
   format q21d_refusal REFUSAL.;
   format q21e_refusal REFUSAL.;
   format       q22 Q22F.;
   format       q23 Q23F.;
   format q24_codes Q24_CODES.;
   format       q25 Q25F.;
   format       q26 Q26F.;
   format       q27 Q27F.;
   format       q28 Q28F.;
   format       q29 Q29F.;
   format       q30 Q30F.;
   format     q31_1 Q31_1F.;
   format     q31_2 Q31_2F.;
   format     q31_3 Q31_3F.;
   format     q31_4 Q31_4F.;
   format     q31_5 Q31_5F.;
   format     q31_6 Q31_6F.;
   format     q31_7 Q31_7F.;
   format     q31_8 Q31_8F.;
   format     q31_9 Q31_9F.;
   format q31_other_text_entered YES_NO.;
   format       q32 Q32F.;
   format     q33_1 Q33_1F.;
   format     q33_2 Q33_2F.;
   format     q33_3 Q33_3F.;
   format     q33_4 Q33_4F.;
   format     q33_5 Q33_5F.;
   format     q33_6 Q33_6F.;
   format     q33_7 Q33_7F.;
   format q33_other_text_entered YES_NO.;
   format       q34 Q34F.;
   format q35_codes Q35_CODES.;
   format q35_text_entered YES_NO.;
   format q24_met_online SUMMARY_Q24_INTERNET.;
   format q24_R_cowork YES_NO.;
   format q24_R_friend YES_NO.;
   format q24_R_family YES_NO.;
   format q24_R_sig_other YES_NO.;
   format q24_R_neighbor YES_NO.;
   format q24_P_cowork YES_NO.;
   format q24_P_friend YES_NO.;
   format q24_P_family YES_NO.;
   format q24_P_sig_other YES_NO.;
   format q24_P_neighbor YES_NO.;
   format q24_btwn_I_cowork YES_NO.;
   format q24_btwn_I_friend YES_NO.;
   format q24_btwn_I_family YES_NO.;
   format q24_btwn_I_sig_other YES_NO.;
   format q24_btwn_I_neighbor YES_NO.;
   format q24_school YES_NO.;
   format q24_college YES_NO.;
   format q24_military YES_NO.;
   format q24_church YES_NO.;
   format q24_vol_org YES_NO.;
   format q24_customer YES_NO.;
   format q24_bar_restaurant YES_NO.;
   format q24_internet_dating YES_NO.;
   format q24_internet_social_networking YES_NO.;
   format q24_internet_game YES_NO.;
   format q24_internet_chat YES_NO.;
   format q24_internet_community YES_NO.;
   format q24_internet_other YES_NO.;
   format q24_public YES_NO.;
   format q24_private_party YES_NO.;
   format q24_blind_date YES_NO.;
   format q24_vacation YES_NO.;
   format q24_singles_service_non_internet YES_NO.;
   format q24_business_trip YES_NO.;
   format q24_work_neighbor YES_NO.;
   format q24_fam_sister_active YES_NO.;
   format q24_fam_brother_active YES_NO.;
   format q24_fam_mother_active YES_NO.;
   format q24_fam_father_active YES_NO.;
   format q24_fam_other_active YES_NO.;
   format q24_fam_cousins_active YES_NO.;
   format q24_fam_aunt_niece_active YES_NO.;
   format q24_fam_uncle_nephew_active YES_NO.;
   format q24_fam_grandmother_active YES_NO.;
   format q24_fam_grandfather_active YES_NO.;
   format q24_fam_sister_passive YES_NO.;
   format q24_fam_brother_passive YES_NO.;
   format q24_fam_mother_passive YES_NO.;
   format q24_fam_father_passive YES_NO.;
   format q24_fam_other_passive YES_NO.;
   format q24_fam_cousins_passive YES_NO.;
   format q24_fam_aunt_niece_passive YES_NO.;
   format q24_fam_uncle_nephew_passive YES_NO.;
   format q24_fam_grandmother_passive YES_NO.;
   format q24_fam_grandfather_passive YES_NO.;
   format q24_fam_female YES_NO.;
   format q24_fam_male YES_NO.;
   format marrynotreally M_NOT_REALLY.;
   format civilnotreally NOT_REALLY.;
   format partner_deceased PARTNER_DECEASED.;
   format partner_religion_reclassified Q7B.;
   format partner_religion_child_reclass Q8B.;
   format own_religion_child_reclass Q13B.;
   format how_met_online HOW_MET_ONLINE_LBL.;
   format either_internet YES_NO.;
   format either_internet_adjusted EITHER_INTERNET_ADJUSTED_LBL.;
   format same_sex_couple SAME_SEX_COUPLE.;
   format potential_partner_gender_recodes Q4F.;
   format alt_partner_gender Q4F.;
   format how_long_ago_first_met_cat HOW_LONG_AGO_FIRST_MET_CAT.;
   format respondent_race RACE_LBL.;
   format partner_race RACE_LBL.;
   format met_through_friends FRIENDS.;
   format met_through_family FAMILY.;
   format met_through_as_neighbors NEIGHBORS.;
   format respondent_religion_at_16 Q13B.;
   format respondent_relig_16_cat RELIG_CAT.;
   format partner_religion_at_16 Q7B.;
   format partner_relig_16_cat RELIG_CAT.;
   format   married MARRIED.;
   format parental_approval PARENTAL_APPROVAL.;
   format home_country_recode Q15A1F.;
   format US_raised US_RAISED.;
   format relationship_quality RELATIONSHIP_QUALITY.;
   format coresident YES_NO.;
   format pp2_afterp1 P2_AFTERP1F.;
   format pp2_pphhhead W2C_PPHHHEAD.;
   format pp2_pphhsize W2C_LABB.;
   format pp2_pphouse W2C_PPHOUSE.;
   format pp2_ppincimp W2C_PPINCIMP.;
   format pp2_ppmarit W2C_PPMARIT.;
   format pp2_ppmsacat W2C_PPMSACAT.;
   format pp2_ppeduc W2C_PPEDUC.;
   format pp2_ppeducat W2C_PPEDUCAT.;
   format pp2_ppethm W2C_PPETHM.;
   format pp2_ppreg4 W2C_PPREG4F.;
   format pp2_ppreg9 W2C_PPREG9F.;
   format pp2_pprent W2C_PPRENT.;
   format pp2_ppt01 W2C_LABB.;
   format pp2_ppt1317 W2C_LABB.;
   format pp2_ppt18ov W2C_LABB.;
   format pp2_ppt25 W2C_LABB.;
   format pp2_ppt612 W2C_LABB.;
   format pp2_ppwork W2C_PPWORK.;
   format pp2_ppnet W2C_PPNET.;
   format  pp_igdr1 W2C_IGDR1F.;
   format pp_ieduc1 W2C_IEDUC1F.;
   format pp2_igdr2 W2C_IGDR2F.;
   format pp2_ieduc2 W2C_IEDUC2F.;
   format w2_deceased W2C_DECEASED.;
   format w2_multiname W2C_MULTINAME.;
   format w2_panelstat W2C_PANELSTAT.;
   format w2_donotcontact W2C_DONOTCONTACT.;
   format w2_assigned W2C_ASSIGNED.;
   format w2_f1complete W2C_F1COMPLETE.;
   format w2_xmarry W2C_XMARRY.;
   format    w2_xss W2C_XSS.;
   format w2_source W2C_SOURCE.;
   format     w2_q1 W2C_Q1F.;
   format     w2_q2 W2C_Q2F.;
   format     w2_q3 W2C_Q3F.;
   format     w2_q4 W2C_Q4F.;
   format     w2_q5 W2C_Q5F.;
   format     w2_q6 W2C_Q6F.;
   format     w2_q7 W2C_Q7F.;
   format     w2_q8 W2C_Q8F.;
   format     w2_q9 W2C_Q9F.;
   format    w2_q10 W2C_Q10F.;
   format w2_broke_up BROKE_UP.;
   format pp3_pphhhead PPHHHEAD.;
   format pp3_pphhsize LABB.;
   format pp3_pphouse PPHOUSE.;
   format pp3_ppincimp PPINCIMP.;
   format pp3_ppmarit PPMARIT.;
   format pp3_ppmsacat PPMSACAT.;
   format pp3_pprent PPRENT.;
   format pp3_ppreg4 PPREG4F.;
   format pp3_ppreg9 PPREG9F.;
   format interstate_mover_pp1_pp2 INTERSTATE_MOVER.;
   format interstate_mover_pp2_pp3 INTERSTATE_MOVER.;
   format interstate_mover_pp1_pp3 INTERSTATE_MOVER.;
   format pp3_ppt01 LABB.;
   format pp3_ppt1317 LABB.;
   format pp3_ppt18ov LABB.;
   format pp3_ppt25 LABB.;
   format pp3_ppt612 LABB.;
   format pp3_ppwork PPWORK.;
   format pp3_ppnet PPNET.;
   format pp3_ppeduc PPEDUC.;
   format pp3_ppeducat PPEDUCAT.;
   format pp3_ppethm PPETHM.;
   format pp3_newer PP3_NEWER.;
   format w2w3_combo_breakup COMBO_BREAKUP.;
   format w3_broke_up W3_BROKEUP_ACTUAL.;
   format w3_xpartnered W3_XQUALIFIED.;
   format w3_xdeceased PARTNER_DECEASED.;
   format w3_multiname W3_MULTINAME.;
   format    w3_xss W3_XSS.;
   format  w3_xlast W3_XLAST.;
   format w3_xqualified W3_XQUALIFIED.;
   format w3_status W3_STATUS.;
   format w3_complete W3_COMPLETE.;
   format w3_source W3_SOURCE.;
   format w3_xmarry XMARRY.;
   format  w3_xtype XTYPE.;
   format     w3_q1 W3_Q1F.;
   format     w3_q2 W3_Q2F.;
   format     w3_q3 W3_Q3F.;
   format     w3_q4 W3_Q4F.;
   format w3_mbtiming_year MBTIMING.;
   format w3_mbtiming_month MONTH.;
   format     w3_q5 W3_Q5F.;
   format     w3_q6 W3_Q6F.;
   format     w3_q7 W3_Q7F.;
   format     w3_q8 W3_Q8F.;
   format     w3_q9 W3_Q9F.;
   format    w3_q10 W3_Q10F.;
   format w3_nonmbtiming_year NONMBTIM.;
   format w3_nonmbtiming_month MONTH.;
quit;
